package pojos;
// Generated 13/11/2016 12:13:33 by Hibernate Tools 4.3.1



/**
 * Acidente generated by hbm2java
 */
public class Acidente  implements java.io.Serializable {


     private int idAcidente;
     private Periodo periodo;
     private Tipoacidente tipoacidente;
     private Trecho trecho;
     private String status;
     private String classificacaoAcidente;
     private String sentido;
     private Short qtdMortos;
     private Short qtdFeridosGraves;
     private Short qtdFeridosLeves;
     private Short qtdIlesos;

    public Acidente() {
    }

	
    public Acidente(int idAcidente) {
        this.idAcidente = idAcidente;
    }
    public Acidente(int idAcidente, Periodo periodo, Tipoacidente tipoacidente, Trecho trecho, String status, String classificacaoAcidente, String sentido, Short qtdMortos, Short qtdFeridosGraves, Short qtdFeridosLeves, Short qtdIlesos) {
       this.idAcidente = idAcidente;
       this.periodo = periodo;
       this.tipoacidente = tipoacidente;
       this.trecho = trecho;
       this.status = status;
       this.classificacaoAcidente = classificacaoAcidente;
       this.sentido = sentido;
       this.qtdMortos = qtdMortos;
       this.qtdFeridosGraves = qtdFeridosGraves;
       this.qtdFeridosLeves = qtdFeridosLeves;
       this.qtdIlesos = qtdIlesos;
    }
   
    public int getIdAcidente() {
        return this.idAcidente;
    }
    
    public void setIdAcidente(int idAcidente) {
        this.idAcidente = idAcidente;
    }
    public Periodo getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Periodo periodo) {
        this.periodo = periodo;
    }
    public Tipoacidente getTipoacidente() {
        return this.tipoacidente;
    }
    
    public void setTipoacidente(Tipoacidente tipoacidente) {
        this.tipoacidente = tipoacidente;
    }
    public Trecho getTrecho() {
        return this.trecho;
    }
    
    public void setTrecho(Trecho trecho) {
        this.trecho = trecho;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getClassificacaoAcidente() {
        return this.classificacaoAcidente;
    }
    
    public void setClassificacaoAcidente(String classificacaoAcidente) {
        this.classificacaoAcidente = classificacaoAcidente;
    }
    public String getSentido() {
        return this.sentido;
    }
    
    public void setSentido(String sentido) {
        this.sentido = sentido;
    }
    public Short getQtdMortos() {
        return this.qtdMortos;
    }
    
    public void setQtdMortos(Short qtdMortos) {
        this.qtdMortos = qtdMortos;
    }
    public Short getQtdFeridosGraves() {
        return this.qtdFeridosGraves;
    }
    
    public void setQtdFeridosGraves(Short qtdFeridosGraves) {
        this.qtdFeridosGraves = qtdFeridosGraves;
    }
    public Short getQtdFeridosLeves() {
        return this.qtdFeridosLeves;
    }
    
    public void setQtdFeridosLeves(Short qtdFeridosLeves) {
        this.qtdFeridosLeves = qtdFeridosLeves;
    }
    public Short getQtdIlesos() {
        return this.qtdIlesos;
    }
    
    public void setQtdIlesos(Short qtdIlesos) {
        this.qtdIlesos = qtdIlesos;
    }




}


