package pojos;
// Generated 13/11/2016 12:13:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cidade generated by hbm2java
 */
public class Cidade  implements java.io.Serializable {


     private int idCidade;
     private String uf;
     private String estado;
     private String municipio;
     private Set trechos = new HashSet(0);

    public Cidade() {
    }

	
    public Cidade(int idCidade) {
        this.idCidade = idCidade;
    }
    public Cidade(int idCidade, String uf, String estado, String municipio, Set trechos) {
       this.idCidade = idCidade;
       this.uf = uf;
       this.estado = estado;
       this.municipio = municipio;
       this.trechos = trechos;
    }
   
    public int getIdCidade() {
        return this.idCidade;
    }
    
    public void setIdCidade(int idCidade) {
        this.idCidade = idCidade;
    }
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }
    public Set getTrechos() {
        return this.trechos;
    }
    
    public void setTrechos(Set trechos) {
        this.trechos = trechos;
    }




}


