package pojos;
// Generated 13/11/2016 12:13:33 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Periodo generated by hbm2java
 */
public class Periodo  implements java.io.Serializable {


     private int idPeriodo;
     private Short ano;
     private String anoTrimestre;
     private Integer dataAcidente;
     private Date dataHoraRegistroOcorrencia;
     private Set acidentes = new HashSet(0);

    public Periodo() {
    }

	
    public Periodo(int idPeriodo) {
        this.idPeriodo = idPeriodo;
    }
    public Periodo(int idPeriodo, Short ano, String anoTrimestre, Integer dataAcidente, Date dataHoraRegistroOcorrencia, Set acidentes) {
       this.idPeriodo = idPeriodo;
       this.ano = ano;
       this.anoTrimestre = anoTrimestre;
       this.dataAcidente = dataAcidente;
       this.dataHoraRegistroOcorrencia = dataHoraRegistroOcorrencia;
       this.acidentes = acidentes;
    }
   
    public int getIdPeriodo() {
        return this.idPeriodo;
    }
    
    public void setIdPeriodo(int idPeriodo) {
        this.idPeriodo = idPeriodo;
    }
    public Short getAno() {
        return this.ano;
    }
    
    public void setAno(Short ano) {
        this.ano = ano;
    }
    public String getAnoTrimestre() {
        return this.anoTrimestre;
    }
    
    public void setAnoTrimestre(String anoTrimestre) {
        this.anoTrimestre = anoTrimestre;
    }
    public Integer getDataAcidente() {
        return this.dataAcidente;
    }
    
    public void setDataAcidente(Integer dataAcidente) {
        this.dataAcidente = dataAcidente;
    }
    public Date getDataHoraRegistroOcorrencia() {
        return this.dataHoraRegistroOcorrencia;
    }
    
    public void setDataHoraRegistroOcorrencia(Date dataHoraRegistroOcorrencia) {
        this.dataHoraRegistroOcorrencia = dataHoraRegistroOcorrencia;
    }
    public Set getAcidentes() {
        return this.acidentes;
    }
    
    public void setAcidentes(Set acidentes) {
        this.acidentes = acidentes;
    }




}


