package pojos;
// Generated 13/11/2016 12:13:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rodovia generated by hbm2java
 */
public class Rodovia  implements java.io.Serializable {


     private int idRodovia;
     private Short br;
     private Set trechos = new HashSet(0);

    public Rodovia() {
    }

	
    public Rodovia(int idRodovia) {
        this.idRodovia = idRodovia;
    }
    public Rodovia(int idRodovia, Short br, Set trechos) {
       this.idRodovia = idRodovia;
       this.br = br;
       this.trechos = trechos;
    }
   
    public int getIdRodovia() {
        return this.idRodovia;
    }
    
    public void setIdRodovia(int idRodovia) {
        this.idRodovia = idRodovia;
    }
    public Short getBr() {
        return this.br;
    }
    
    public void setBr(Short br) {
        this.br = br;
    }
    public Set getTrechos() {
        return this.trechos;
    }
    
    public void setTrechos(Set trechos) {
        this.trechos = trechos;
    }




}


