package pojos;
// Generated 13/11/2016 12:13:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoacidente generated by hbm2java
 */
public class Tipoacidente  implements java.io.Serializable {


     private int idTipoacidente;
     private String tipoAcidente;
     private Set acidentes = new HashSet(0);

    public Tipoacidente() {
    }

	
    public Tipoacidente(int idTipoacidente) {
        this.idTipoacidente = idTipoacidente;
    }
    public Tipoacidente(int idTipoacidente, String tipoAcidente, Set acidentes) {
       this.idTipoacidente = idTipoacidente;
       this.tipoAcidente = tipoAcidente;
       this.acidentes = acidentes;
    }
   
    public int getIdTipoacidente() {
        return this.idTipoacidente;
    }
    
    public void setIdTipoacidente(int idTipoacidente) {
        this.idTipoacidente = idTipoacidente;
    }
    public String getTipoAcidente() {
        return this.tipoAcidente;
    }
    
    public void setTipoAcidente(String tipoAcidente) {
        this.tipoAcidente = tipoAcidente;
    }
    public Set getAcidentes() {
        return this.acidentes;
    }
    
    public void setAcidentes(Set acidentes) {
        this.acidentes = acidentes;
    }




}


