package pojos;
// Generated 13/11/2016 12:13:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Trecho generated by hbm2java
 */
public class Trecho  implements java.io.Serializable {


     private int idTrecho;
     private Cidade cidade;
     private Rodovia rodovia;
     private String trecho;
     private Set acidentes = new HashSet(0);

    public Trecho() {
    }

	
    public Trecho(int idTrecho) {
        this.idTrecho = idTrecho;
    }
    public Trecho(int idTrecho, Cidade cidade, Rodovia rodovia, String trecho, Set acidentes) {
       this.idTrecho = idTrecho;
       this.cidade = cidade;
       this.rodovia = rodovia;
       this.trecho = trecho;
       this.acidentes = acidentes;
    }
   
    public int getIdTrecho() {
        return this.idTrecho;
    }
    
    public void setIdTrecho(int idTrecho) {
        this.idTrecho = idTrecho;
    }
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }
    public Rodovia getRodovia() {
        return this.rodovia;
    }
    
    public void setRodovia(Rodovia rodovia) {
        this.rodovia = rodovia;
    }
    public String getTrecho() {
        return this.trecho;
    }
    
    public void setTrecho(String trecho) {
        this.trecho = trecho;
    }
    public Set getAcidentes() {
        return this.acidentes;
    }
    
    public void setAcidentes(Set acidentes) {
        this.acidentes = acidentes;
    }




}


